#BASICS
baseurl: /leomilgroup
exclude: ['README.md']

#NAVIGATION
navigation:
- text: Our Story
  url: /our-story
- text: Brands and Licenses
  url: /brands-licenses
- text: Global Presence
  url: /global-presence
- text: News
  url: /news
- text: Contact
  url: /contact
- text: Collection
  external_url: https://collection.leomilgroup.com