#BASICS
baseurl: /leomilgroup
exclude: ['README.md']

#NAVIGATION
navigation:
- text: Our Story
  url: /our-story
- text: Brands and Licenses
  url: /brands-licenses
- text: Global Presence
  url: /global-presence
- text: Test
  url: /news1
- text: Contact
  url: /contact
- text: Collection
  url: /collection